enum PermissionEnum {
  'dashboard_admin',
  'dashboard_user',
  'login_user.store',
  'users.index',
  'users.store',
  'users.update',
  'users.delete',
  'admin.index',
  'admin.store',
  'admin.update',
  'admin.delete',
  'permissions.index',
  'permissions.delete',
  'permissions.store',
  'permissions.update',
  'roles.index',
  'roles.delete',
  'roles.store',
  'roles.update',
  'roles_unassign.store',
  'roles_assign.store',
  'roles.detail',
  'all_url_shortener.index',
  'url_shortener.delete',
  'url_shortener.store',
  'url_shortener.update',
  'pengumuman.index',
  'pengumuman.store',
  'pengumuman.update',
  'pengumuman.delete',
  'pre_event.index',
  // Journalistik
  'jurnalistik.index',
  'jurnalistik_join.store',
  'jurnalistik_team.delete',
  'jurnalistik_ketua.store',
  'jurnalistik_member.store',
  'admin_jurnalistik.index',
  'admin_jurnalistik.detail',
  'pembayaran_jurnalistik.store',
  // KTI
  'kti.index',
  'kti.store',
  // Robotik
  'robot_in_action.index',
  'robot_in_action.store',
}

export type PermissionList = Array<keyof typeof PermissionEnum>;
